### ISSUE TITLE
cleanDBs() startup error

### ISSUE THREAD

**Issue by schollz** [schollz/find#2]
* I install python 3.5 on 64-bit windows 8.1
* I install all packages, except numpy==1.9.2, due to error:
--- ValueError: Could not lock sequences...
* So I install numpy==1.9.3
* Then I run: python server.py install (Your instruction says: setup.py, instead of server.py)

```
============================================
..................
Traceback (most recent call last):
  File "server.py", line 8, in <module>
    from libraries.routing import *
  File "C:\Users\Jerry\Desktop\find-master\libraries\routing.py", line 1049, in <module>
    launch()
  File "C:\Users\Jerry\Desktop\find-master\libraries\routing.py", line 1041, in launch
    cleanDBs()
  File "C:\Users\Jerry\Desktop\find-master\libraries\routing.py", line 1004, in cleanDBs
    group = name.split('data/')[1].split('.db')[0]
IndexError: list index out of range
==============================================
```

**Comment by schollz** [comment]
So there were a number of errors here.

1) "setup.py" was not present for installation. I've now included the setup.py which should be used for installation, as it requires downloading resources from the releases.
2) `IndexError: list index out of range` is occuring because I'm splitting strings based on forward slashes (linux) not backward slashes (windows). Thus there is no splitting occurring. This has been fixed. However, this eludes to a bigger error - in that I use a lot of unix commands (rm/unzip) which are not present in windows. Until I have removed all these, I would say that this version is not compatible with windows. However it is compatible with Cygwin on Windows (assuming Python3 installation + wget + unzip).
